---
title: "Gráficos Básicos"
---

Histograma
```{r}
trees
hist(trees$Height)
hist(trees$Height, main = "Arvores", ylab = "Frequencia", xlab = "Altura", col = "blue")
hist(trees$Height, main = "Arvores", ylab = "Frequencia", xlab = "Altura", col = "blue", density = 20, breaks = 20)
```

Densidade
```{r}
densidade = density(trees$Height)
plot(densidade)
```
Densidade sobre o histograma, parametro par
```{r}
hist(trees$Height, main = NULL, xlab = NULL, ylab = NULL)
par(new = TRUE)
plot(densidade)
```
Dispersão
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main = "Árvores")
plot(trees$Girth, trees$Volume, main = "Árvores", xlab = "Volume", ylab = "Circunferência", col = "blue")
#pch muda o elemento gráfico
plot(trees$Girth, trees$Volume, main = "Árvores", xlab = "Volume", ylab = "Circunferência", col = "blue", pch = 20)
```


Muda tipo
```{r}
plot(trees$Girth, trees$Volume, main="árvores", xlab = "Volume", ylab = "Circunferência", col = "blue", pch = 20, type = "l" )
```
Tremulação, diminui sobre posição
```{r}
plot(jitter(trees$Girth), trees$Volume, main = "Árvores", xlab = "Volume", ylab = "Circunferência", col = "blue")
```
Legenda com dimensão categorica
```{r}
CO2
plot(CO2$conc, CO2$uptake, pch = 20, col = CO2$Treatment)
legend("bottomright", legend = c("nonchilled", "chilled"), cex = 1, fill = c("black", "red"))
```

Novos dado
```{r}
plot(trees)
```

Divisao da tela
```{r}
split.screen(figs = c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all = TRUE)
```













